/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    links: Link;
    posts: Post;
    comments: Comment;
    votes: Vote;
    bookmarks: Bookmark;
    subfeeds: Subfeed;
    discoveries: Discovery;
    reports: Report;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    links: {
      relatedComments: 'comments';
      saves: 'bookmarks';
    };
    posts: {
      relatedComments: 'comments';
      saves: 'bookmarks';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    votes: VotesSelect<false> | VotesSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    subfeeds: SubfeedsSelect<false> | SubfeedsSelect<true>;
    discoveries: DiscoveriesSelect<false> | DiscoveriesSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  bio?: string | null;
  avatar?: (number | null) | Media;
  trustLevel?: ('newcomer' | 'regular' | 'recognized' | 'trusted' | 'veteran' | 'curator' | 'pillar' | 'legend') | null;
  titles?: string[] | null;
  badges?: string[] | null;
  reputationHidden?: number | null;
  reputationPublicLabel?: string | null;
  securityScore?: number | null;
  isUploader?: boolean | null;
  isEditor?: boolean | null;
  isModerator?: boolean | null;
  isAdmin?: boolean | null;
  streakDays?: number | null;
  lastActiveAt?: string | null;
  discoveryScore?: number | null;
  contributionScore?: number | null;
  interactionScore?: number | null;
  moderationScore?: number | null;
  legacyContributionScore?: number | null;
  roles?: ('admin' | 'editor' | 'moderator' | 'uploader' | 'user')[] | null;
  settings: {
    nsfw?: boolean | null;
    language: 'en' | 'sv';
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  title: string;
  slug?: string | null;
  url: string;
  description?: string | null;
  nsfw?: boolean | null;
  type: 'article' | 'video' | 'image' | 'audio' | 'game';
  feed?: ('main' | 'user' | 'subfeed') | null;
  subfeed?: (number | null) | Subfeed;
  tags?: string[] | null;
  user: number | User;
  votes?: number | null;
  score?: number | null;
  rankingScore?: number | null;
  controversyScore?: number | null;
  discoveryMomentum?: number | null;
  engagementVelocity?: number | null;
  upvotes?: number | null;
  downvotes?: number | null;
  commentsCount?: number | null;
  sharesCount?: number | null;
  uniqueCommenters?: number | null;
  trustedInteractions?: number | null;
  spamProbability?: number | null;
  ragebaitProbability?: number | null;
  featured?: boolean | null;
  breaking?: boolean | null;
  controversial?: boolean | null;
  moderationStatus?: ('pending' | 'approved' | 'removed') | null;
  clickCount?: number | null;
  /**
   * Comments related to this link
   */
  relatedComments?: {
    docs?: (number | Comment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users who bookmarked this link
   */
  saves?: {
    docs?: (number | Bookmark)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subfeeds".
 */
export interface Subfeed {
  id: number;
  name: string;
  slug: string;
  description: string;
  avatar?: (number | null) | Media;
  banner?: (number | null) | Media;
  rules?: string | null;
  theme?: string | null;
  moderators: (number | User)[];
  members?: (number | User)[] | null;
  reputation?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  comment: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  user: number | User;
  link?: (number | null) | Link;
  post?: (number | null) | Post;
  parentComment?: (number | null) | Comment;
  upvotes?: number | null;
  downvotes?: number | null;
  score?: number | null;
  controversyScore?: number | null;
  moderationStatus?: ('visible' | 'pending' | 'removed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'link' | 'article' | 'image' | 'video' | 'discussion';
  nsfw?: boolean | null;
  user: number | User;
  feed: 'main' | 'user' | 'subfeed';
  subfeed?: (number | null) | Subfeed;
  tags?: string[] | null;
  votes?: number | null;
  score?: number | null;
  rankingScore?: number | null;
  controversyScore?: number | null;
  discoveryMomentum?: number | null;
  engagementVelocity?: number | null;
  upvotes?: number | null;
  downvotes?: number | null;
  commentsCount?: number | null;
  sharesCount?: number | null;
  uniqueCommenters?: number | null;
  trustedInteractions?: number | null;
  spamProbability?: number | null;
  ragebaitProbability?: number | null;
  featured?: boolean | null;
  breaking?: boolean | null;
  controversial?: boolean | null;
  status?: ('published' | 'pending' | 'removed') | null;
  /**
   * Comments related to this post
   */
  relatedComments?: {
    docs?: (number | Comment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users who bookmarked this post
   */
  saves?: {
    docs?: (number | Bookmark)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: number;
  user: number | User;
  link?: (number | null) | Link;
  post?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes".
 */
export interface Vote {
  id: number;
  user: number | User;
  link?: (number | null) | Link;
  post?: (number | null) | Post;
  vote: 'up' | 'down';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discoveries".
 */
export interface Discovery {
  id: number;
  user: number | User;
  post: number | Post;
  discoveredAt: string;
  engagementGenerated?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  reporter: number | User;
  targetType: 'post' | 'comment' | 'link' | 'user';
  targetId: string;
  targetPost?: (number | null) | Post;
  targetComment?: (number | null) | Comment;
  targetLink?: (number | null) | Link;
  targetUser?: (number | null) | User;
  reason: 'spam' | 'abuse' | 'broken_link' | 'harassment' | 'nsfw' | 'other';
  details?: string | null;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy?: (number | null) | User;
  fastTracked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'votes';
        value: number | Vote;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: number | Bookmark;
      } | null)
    | ({
        relationTo: 'subfeeds';
        value: number | Subfeed;
      } | null)
    | ({
        relationTo: 'discoveries';
        value: number | Discovery;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  bio?: T;
  avatar?: T;
  trustLevel?: T;
  titles?: T;
  badges?: T;
  reputationHidden?: T;
  reputationPublicLabel?: T;
  securityScore?: T;
  isUploader?: T;
  isEditor?: T;
  isModerator?: T;
  isAdmin?: T;
  streakDays?: T;
  lastActiveAt?: T;
  discoveryScore?: T;
  contributionScore?: T;
  interactionScore?: T;
  moderationScore?: T;
  legacyContributionScore?: T;
  roles?: T;
  settings?:
    | T
    | {
        nsfw?: T;
        language?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url?: T;
  description?: T;
  nsfw?: T;
  type?: T;
  feed?: T;
  subfeed?: T;
  tags?: T;
  user?: T;
  votes?: T;
  score?: T;
  rankingScore?: T;
  controversyScore?: T;
  discoveryMomentum?: T;
  engagementVelocity?: T;
  upvotes?: T;
  downvotes?: T;
  commentsCount?: T;
  sharesCount?: T;
  uniqueCommenters?: T;
  trustedInteractions?: T;
  spamProbability?: T;
  ragebaitProbability?: T;
  featured?: T;
  breaking?: T;
  controversial?: T;
  moderationStatus?: T;
  clickCount?: T;
  relatedComments?: T;
  saves?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  type?: T;
  nsfw?: T;
  user?: T;
  feed?: T;
  subfeed?: T;
  tags?: T;
  votes?: T;
  score?: T;
  rankingScore?: T;
  controversyScore?: T;
  discoveryMomentum?: T;
  engagementVelocity?: T;
  upvotes?: T;
  downvotes?: T;
  commentsCount?: T;
  sharesCount?: T;
  uniqueCommenters?: T;
  trustedInteractions?: T;
  spamProbability?: T;
  ragebaitProbability?: T;
  featured?: T;
  breaking?: T;
  controversial?: T;
  status?: T;
  relatedComments?: T;
  saves?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  comment?: T;
  user?: T;
  link?: T;
  post?: T;
  parentComment?: T;
  upvotes?: T;
  downvotes?: T;
  score?: T;
  controversyScore?: T;
  moderationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes_select".
 */
export interface VotesSelect<T extends boolean = true> {
  user?: T;
  link?: T;
  post?: T;
  vote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  user?: T;
  link?: T;
  post?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subfeeds_select".
 */
export interface SubfeedsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  avatar?: T;
  banner?: T;
  rules?: T;
  theme?: T;
  moderators?: T;
  members?: T;
  reputation?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discoveries_select".
 */
export interface DiscoveriesSelect<T extends boolean = true> {
  user?: T;
  post?: T;
  discoveredAt?: T;
  engagementGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  targetPost?: T;
  targetComment?: T;
  targetLink?: T;
  targetUser?: T;
  reason?: T;
  details?: T;
  status?: T;
  reviewedBy?: T;
  fastTracked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'links';
      value: number | Link;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}